theme = "PaperMod"
publishDir = "docs"
baseURL = "https://lishehao-ctrl.github.io/"
title = "Shehao Li"

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10

  [[menu.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 20

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  mainSections = []
  ShowPostTags = false

  [params.profileMode]
    enabled = false
    title = "Shehao (Oliver) Li"
    subtitle = "Math-CS @ UCSD.\nInterested in Machine Learning & Software Engineering."

  [params.label]
    text = "Shehao Li"
    icon = ""
    iconHeight = 18
